### ISSUE TITLE
could we rename the package to all lowercase?

### ISSUE THREAD

**Issue by maelle** [EMODnet/emodnet.wfs#163]
@salvafern Any thought? Lowercase is easier to type. Now is a good time to rename the package (as opposed to after a first CRAN release for instance)

https://devguide.ropensci.org/pkg_building.html#naming-your-package

**Comment by maelle** [comment]
@salvafern said yes

**Comment by maelle** [comment]
I am having second thoughts! "emodnetwfs" is probably not great for screen-reader users. What about "emodnetWFS"? or "emodnetfeatures"? Who else could we ask for a third opinion?

**Comment by maelle** [comment]
emodfeat

**Comment by maelle** [comment]
what I have no doubt about is that the current name is hard to type.

**Comment by maelle** [comment]
emodnet.features

**Comment by maelle** [comment]
maybe even better would be an acronym

**Comment by maelle** [comment]
pufferfish = has P like package, f like feature, e like emodnet, s like service.

**Comment by maelle** [comment]
starfish in honor of the EU flag

**Comment by maelle** [comment]
I still think we should get an opinion from others. A name related to the ocean, with a paired name for EMODnetWCS would be really nice.

**Comment by maelle** [comment]
or a boat name starting with f for WFS, one starting with c for WCS.

https://en.wikipedia.org/wiki/Category:Boat_types

**Comment by maelle** [comment]
- **fer**ry (**f**eature service for **e**modnet, in **R**)
- **co**bl**e** (**co**verage service for **e**modnet)

**Comment by maelle** [comment]
althought it might seem insulting than one of those boats is clearly smaller.

**Comment by maelle** [comment]
@salvafern thoughts?

**Comment by JoBeja** [comment]
Hey, I think that it would be good to clearly identify the packages as EMODnet... If I have any ideas I'll put them through

**Comment by maelle** [comment]
@JoBeja that's a good point. Now, could it be enough to state this clearly in the documentation and metadata?

The problem with emodnetwfs is that it could at first look hard to pronounce and remember.

**Comment by JoBeja** [comment]
@maelle no I don't think it is enough. As I see it, it's mainly a matter of branding. I think our R packages don't have a lot of visibility and using a name that immediately identifies them as EMODnet is important.
Acronym pronounciation varies across the globe, some countries read each letter separately, others read it as if it was a word, we're not going to please everyone, whatever choice we make.

**Comment by maelle** [comment]
then what about emodnet.wfs? I don't like dotted names in general but I'd find that easier to remember than EMODnetWFS.

**Comment by salvafern** [comment]
Since a new gen of ogc services is coming and they seem to partially drop the WCS, WFS etc for OGC API - Coverages or Features, how about naming the package closer to these?

e.g. emodnetfeat, emodnetfeatures

likewise emodnetcov, emodnetcoverages etc

See https://ogcapi.ogc.org/#standards

**Comment by maelle** [comment]
:wave: @here! I'm happy to go with whatever you two find the most appropriate for the project itself and for most likely users. 

I'd like to submit the package in August after my summer vacation (the week of the 19th for instance). Could you two get back to me before then?

**Comment by JoBeja** [comment]
Hi,
As long as emodnet is in the package name, I don't mind whether it's wcs/wfs or features/coverages. You have more expertise on this than I do, so please go ahead with the option you think is best and written in the way you think is best too.

**Comment by maelle** [comment]
Thanks @JoBeja!

@salvafern what about emodnet.wcs or emodnet.features? Dotted names might not be the best in general but there's for instance aws.s3 and friends.

**Comment by bart-v** [comment]
I vote `emodnetogc`, then we can still use WFS, and move to OGC API whenever needed

**Comment by JoBeja** [comment]
@bart-v they are two packages which work independently, we need two names. Do you have a suggestion?

**Comment by bart-v** [comment]
Which 2 packages?

**Comment by JoBeja** [comment]
EMODnetWCS and EMODnet WFS

**Comment by maelle** [comment]
so they could be

- emodnet.wfs and emodnet.wcs
- emodnet.features and emodnet.coverage
- other propositions welcome

what I feel strongly about is not having a "complicated" lower-case/upper-case mix.

**Comment by maelle** [comment]
@annakrystalli tagging you too :smile_cat:

**Comment by annakrystalli** [comment]
No objection from me to shifting to all lowercase.

I prefer `emodnet.wfs` and 
`emodnet.wcs` but would also be happy with `emodnetwfs` and `emodnetwcs`. Excited to see both on CRAN soon!! 😃

**Comment by maelle** [comment]
@annakrystalli let's get them through software-review first :wink:

**Comment by salvafern** [comment]
Let's go with the dotted version? emodnet.wfs and emodnet.wcs

**Comment by maelle** [comment]
ok let's go for this one!
