### ISSUE TITLE
How to get the package listed from the FAQ

### ISSUE THREAD

**Issue by maelle** [EMODnet/emodnet.wfs#166]
https://emodnet.ec.europa.eu/en/faq-about-downloading-emodnet-data#Downloaddata

**Comment by maelle** [comment]
@salvafern any suggestion?

**Comment by salvafern** [comment]
Hey so I asked and they prefer to include the package there as it is focused solely on the geoviewer and ERDDAP. The package is listed in other places as e.g. here: https://emodnet.ec.europa.eu/en/biology#biology-key-services. 
Would that be sufficient?

**Comment by maelle** [comment]
It's sufficient if you think it is. @JoBeja, any opinion?

**Comment by maelle** [comment]
(Thanks @salvafern!!)

**Comment by salvafern** [comment]
I think it is :)
