### ISSUE TITLE
codecov

### ISSUE THREAD

**Issue by maelle** [EMODnet/emodnet.wfs#171]
@salvafern do you have admin access to https://app.codecov.io/gh/EMODnet? I think the repo might need to be reactivated now that I renamed it.

**Comment by salvafern** [comment]
No I don't have admin access. @bart-v could you have a look?

**Comment by maelle** [comment]
Beside possible reactivation, maybe we also need a token. It can be an organization wide secret (this way we won't need to ask again for emodnet.wcs) https://ropensci.org/blog/2024/05/24/ropensci-news-may-2024/#token-now-needed-for-code-coverage-via-codecov-and-covr-on-github-actions

**Comment by maelle** [comment]
Now the badge is working but having the token might still be a good idea (I fear we might run into rate limits otherwise? Or maybe there is already an organization-side secret?)

**Comment by bart-v** [comment]
There was already an organization-side secret.
Since you asked for a new one, I overwrote it by one I generated
So probably it's broken now...
Can you test?

**Comment by maelle** [comment]
Ok, thanks, sorry. Following https://github.com/EMODnet/emodnet.wfs/actions/runs/10353537203 now

**Comment by maelle** [comment]
ah indeed "Not valid tokenless upload", the new token needs to be stored as new organization-wide secret. So sorry!!

**Comment by bart-v** [comment]
OK done, try now?

**Comment by maelle** [comment]
Weirdly I got the same error again https://github.com/EMODnet/emodnet.wfs/actions/runs/10353537203/job/28690809753#step:6:46 :thinking: (I can't explore more today, sorry)

**Comment by bart-v** [comment]
Seems a bug in codecov
https://github.com/codecov/codecov-action/issues/1487
You need to use version 4.5.0 and not 4

**Comment by maelle** [comment]
Thanks! :popcorn: https://github.com/EMODnet/emodnet.wfs/actions/runs/10365406147

**Comment by bart-v** [comment]
OK, I now used the correct token, i.e. like here
https://github.com/codecov/codecov-action/issues/1537
Seems to work

**Comment by maelle** [comment]
thanks!!
