### ISSUE TITLE
Get a DOI for package

### ISSUE THREAD

**Issue by annakrystalli** [EMODnet/emodnet.wfs#31]
Get a DOI form Zenodo (as [ows4r](https://github.com/eblondel/ows4R) does). Include funding details

**Comment by maelle** [comment]
@salvafern could I assign this issue to you? :innocent:

**Comment by salvafern** [comment]
Yes no problem! I'll have a look

**Comment by salvafern** [comment]
We should create DOIs with a release. @maelle do you want to do a release now or you prefer to wait until some more issues and PR are resolved?

**Comment by maelle** [comment]
I think we should make a release right before rOpenSci submission so the release after that would contain all changes from review, what do you think?

**Comment by salvafern** [comment]
Good for me :) but still not there for the submission to rOpenSci right?

**Comment by maelle** [comment]
yes I think the package needs a bit more work

**Comment by JoBeja** [comment]
Hi @annakrystalli, we are most likely not using Zenodo for this as we have a system in place that allows for the creation of DOIs, so unless our colleagues tell us it's not possible, we will use our own system. 
We already have a metadata record for this package in our system (https://www.vliz.be/en/imis?module=dataset&dasid=6654) and it's replicated in the EMODnet catalogue (https://emodnet.ec.europa.eu/geonetwork/srv/eng/catalog.search#/metadata/6d617269-6e65-696e-666f-000000006654). Salva is requesting clarification from our colleagues.

**Comment by maelle** [comment]
thank you @JoBeja @salvafern!

**Comment by salvafern** [comment]
@maelle I made a PR with some litte changes I noticed.

I think it would be the best to make a new release here on github, and after that I can assign a DOI to that version. Let me know when the package is ready to go and I will do it :rocket:

**Comment by maelle** [comment]
@salvafern thank you!!

I've done the GitHub release.

**Comment by salvafern** [comment]
Here: https://doi.org/10.14284/679

**Comment by maelle** [comment]
thank you!! I'll submit tomorrow then :rocket:
